version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=change-this-in-production
    volumes:
      - ./data:/app/data
    restart: unless-stopped
